mysite/home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('register', views.register, name="register"), # message sample: https://learndjango.com/tutorials/django-signup-tutorial
    path('about', views.TechView.as_view(), name="tech"), # django async with token version: https://youtu.be/28KFBqi2JrA?t=900 
    # path('about', TemplateView.as_view(template_name = "home/tech_list.html"), name="tech"), # javascript async with no token version
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from todo.apis import LoginTodoView, LogoutTodoView
from daisy.apis import LoginView, LogoutView
from django.conf.urls.static import static

urlpatterns = [
    # path('', include('ads.urls')),
    path('', include('home.urls')),
    path('onestop/', include('onestop.urls')),
    path('daisy/', include('daisy.urls')),
    path('api/v1/', include('daisy.api_urls')),
    path('api/v1/auth/login/', LoginView.as_view()),
    path('api/v1/auth/logout/', LogoutView.as_view()),
    path('plant/', include('plant.urls')),
    path('admin/', admin.site.urls),
    # https://learndjango.com/tutorials/django-login-and-logout-tutorial
    # https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views
    path('api/v2/', include('todo.api_urls')),
    path('api/v2/auth/login/', LoginTodoView.as_view()),
    path('api/v2/auth/logout/', LogoutTodoView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# urlpatterns += [
#     re_path(r'^apps/(?P<path>.*)$', serve,
#         {'document_root': os.path.join(BASE_DIR, '../'),
#          'show_indexes': True},
#         name='index_path'
#         ),
# ]

# Serve the favicon -
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# https://itc.tokyo/django/setup-media-root/
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References
# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/onestop/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='onestop'
urlpatterns = [
    path('', views.RecipeListView.as_view(), name='all'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipe/create',
        views.RecipeCreateView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_create'),
    path('recipe/<int:pk>/update',
        views.RecipeUpdateView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_update'),
    path('recipe/<int:pk>/delete',
        views.RecipeDeleteView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_delete'),
    path('recipe-picture/<int:pk>', views.stream_file, name='recipe_picture'),
    path('recipe/<int:pk>/note',
        views.NoteCreateView.as_view(), name='recipe_note_create'),
    path('note/<int:pk>/delete',
        views.NoteDeleteView.as_view(), name='recipe_note_delete'),
    path('recipe/<int:pk>/favorite', views.AddFavoView.as_view(), name='recipe_favorite'),
    path('recipe/<int:pk>/unfavorite', views.DeleteFavoView.as_view(), name='recipe_unfavorite'),
    path('tags/', views.TagListView.as_view(), name='tag_list'), # https://django-taggit.readthedocs.io/en/latest/api.html
    path('tags/<str:name>/recipes', views.RecipeByTagListView.as_view(), name='recipe_by_tag_list'), # https://github.com/jazzband/django-taggit/issues/294
    path('tags/delete/unused-tags', views.remove_all_tags_without_objects, name='delete_unused_tags'),
]

#Use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/onestop/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class Recipe(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    website = models.URLField(max_length=200)
    text = RichTextField(blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    notes = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Note', related_name='notes_owned')

    # Picture
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
                                    help_text='The MIMEType of the file')

    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Favo', related_name='favorite_recipes')

    # Tags
    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Note(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class Favo(models.Model) :
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('recipe', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.recipe.title[:10])

mysite/onestop/forms.py
from django import forms
from onestop.models import Recipe
from django.core.files.uploadedfile import InMemoryUploadedFile
from onestop.humanize import naturalsize
from taggit.forms import TagField

# override django-taggit tags so that they are always lowercase
# https://github.com/jazzband/django-taggit/blob/master/taggit/forms.py
# https://docs.djangoproject.com/en/4.1/ref/forms/validation/
# https://stackoverflow.com/questions/24313201/convert-all-charfield-form-field-inputs-to-lowercase-in-django-forms
class TagCustomField(TagField):
    def to_python(self, value):
        return value.lower()


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # override django-taggit tags so that they are always lowercase
    tags = TagCustomField()

    class Meta:
        model = Recipe
        fields = ['title', 'text', 'website', 'picture', 'tags']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data
        if commit:
            # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
            self.save_m2m()
            instance.save()
                
        return instance

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

class NoteForm(forms.Form):
    note = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

mysite/onestop/views.py
from onestop.models import Recipe, Note, Favo
from onestop.owner import OwnerDetailView, OwnerDeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from onestop.forms import CreateForm, NoteForm
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.humanize.templatetags.humanize import naturaltime
from taggit.models import Tag
from django.views.generic.list import ListView
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt # for add and delete favorites
from django.utils.decorators import method_decorator # for add and delete favorites
from django.db.utils import IntegrityError # for add and delete favorites


class RecipeListView(View):
    # model = Recipe
    # By convention:
    template_name = "onestop/recipe_list.html"

    def get(self, request) :

        favorites = list()
        print(request.path)
        # creating recipe_list based on 1 if there is a serch string
        strval =  request.GET.get("search", False)
        if strval:
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            recipe_list = Recipe.objects.filter(query).select_related().order_by('-updated_at')[:10]
        # or no search string
        else :
            recipe_list = Recipe.objects.all().order_by('-updated_at')[:10]

        for obj in recipe_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        # adding favorite stars
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_recipes.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        ctx = {'recipe_list' : recipe_list, 'favorites': favorites, "search": strval}
        return render(request, self.template_name, ctx)


class RecipeDetailView(OwnerDetailView):
    model = Recipe
    template_name = "onestop/recipe_detail.html"
    
    def get(self, request, pk) :
        x = Recipe.objects.get(id=pk)
        notes = Note.objects.filter(recipe=x).order_by('-updated_at')
        note_form = NoteForm()
        context = { 'recipe' : x, 'notes': notes, 'note_form': note_form }
        return render(request, self.template_name, context)


class RecipeCreateView(LoginRequiredMixin, View):
    template_name = 'onestop/recipe_form.html'
    success_url = reverse_lazy('onestop:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        # Add owner to the model before saving
        recipe = form.save(commit=False)
        recipe.owner = self.request.user
        recipe.save()
        # https://www.dj4e.com/assn/dj4e_ads4.md?PHPSESSID=bd08ca99d78434177e27b51978bafaf9
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this for taggit
        return redirect(self.success_url)


class RecipeUpdateView(LoginRequiredMixin, View):
    template_name = 'onestop/recipe_form.html'
    success_url = reverse_lazy('onestop:all')

    def get(self, request, pk):
        recipe = get_object_or_404(Recipe, id=pk, owner=self.request.user)
        form = CreateForm(instance=recipe)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        recipe = get_object_or_404(Recipe, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=recipe)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        recipe = form.save(commit=False)
        recipe.save()
        # https://www.dj4e.com/assn/dj4e_ads4.md?PHPSESSID=bd08ca99d78434177e27b51978bafaf9
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this for taggit
        return redirect(self.success_url)


class RecipeDeleteView(OwnerDeleteView):
    model = Recipe


def stream_file(request, pk):
    recipe = get_object_or_404(Recipe, id=pk)
    response = HttpResponse()
    response['Content-Type'] = recipe.content_type
    response['Content-Length'] = len(recipe.picture)
    response.write(recipe.picture)
    return response


class NoteCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Recipe, id=pk)
        note = Note(text=request.POST['note'], owner=request.user, recipe=f)
        note.save()
        return redirect(reverse('onestop:recipe_detail', args=[pk]))

class NoteDeleteView(OwnerDeleteView):
    model = Note
    template_name = "onestop/note_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        recipe = self.object.recipe
        return reverse('onestop:recipe_detail', args=[recipe.id])

class TagListView(ListView):
    model = Tag
    template_name = "onestop/tag_list.html"
    context_object_name = 'tag_list'


class RecipeByTagListView(ListView):
    # https://django-taggit.readthedocs.io/en/latest/api.html#filtering
    model = Tag
    template_name = "onestop/recipe_by_tag_list.html"
    context_object_name = 'recipes_by_tag_list'

    def get(self, request, name) :
        x = Tag.objects.get(name=name)
        print(x)
        recipes = Recipe.objects.filter(tags__name__in=[name]).order_by('-updated_at')
        context = {'recipes': recipes, 'tag_name' : name }
        return render(request, self.template_name, context)


def remove_all_tags_without_objects(request):
    success_url = reverse_lazy('onestop:tag_list')
    for tag in Tag.objects.all():
        if tag.taggit_taggeditem_items.count() == 0:
            print('Removing: {}'.format(tag))
            tag.delete()
        else:
            print('Keeping: {}'.format(tag))
    return redirect(success_url) 

# https://docs.djangoproject.com/en/4.1/topics/class-based-views/intro/#decorating-the-class
# https://docs.djangoproject.com/en/4.1/ref/csrf/#module-django.views.decorators.csrf
@method_decorator(csrf_exempt, name='dispatch')
class AddFavoView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Recipe, id=pk)
        fav = Favo(user=request.user, recipe=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Recipe, id=pk)
        try:
            # fav = Fav.objects.get(user=request.user, ad=t).delete()
            Favo.objects.get(user=request.user, recipe=t).delete()
        except Favo.DoesNotExist as e:
            pass

        return HttpResponse()

mysite/onestop/templates/onestop/note_delete.html
{% extends "base_menu.html" %}

{% block content %}
<div class="container">
    <h1>Delete Note</h1>
    <p>Are you sure you want to delete</p>
    <p>{{ note.text }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit"  class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'onestop:recipe_detail' note.recipe.id %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

mysite/onestop/templates/onestop/recipe_by_tag_list.html
{% extends "base_menu.html" %}

{% block content %}
<div class ="container">
    <h1>Recipes with Tag: "{{ tag_name }}"</h1>
    <ul>
        <!-- Iterate over object_list -->
        {% for recipe in recipes %}
        <!-- Display Objects -->
        <li style="display: block;"><a href="{% url 'onestop:recipe_detail' recipe.id %}">{{ recipe.title }}</a></li>
        <!-- If object_list is empty  -->
        {% empty %}
        <li>No recipe yet.</li>
        {% endfor %}
    </ul>
    <br/>
    <p>
        <a href="{% url 'onestop:tag_list' %}">Recipes by Tag</a>
    </p>
</div>
{% endblock %}

mysite/onestop/templates/onestop/recipe_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}
<div class="container">
    <h1>Delete Recipe</h1>
    <p>Are you sure you want to delete the recipe: {{ recipe }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
</div>
{% endblock %}

mysite/onestop/templates/onestop/recipe_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/pic_detail.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    {% if recipe.content_type %}
    <div id="overlay" class="overlay" style="text-align: center;" onclick="document.getElementById('overlay').style.display = 'none';" >
        <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'onestop:recipe_picture' recipe.id %}">
    </div>
    {% endif %}
    <span style="float: right;">
        ({{ recipe.updated_at|naturaltime }})
        {% if recipe.owner == user %}
        <a href="{% url 'onestop:recipe_update' recipe.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'onestop:recipe_delete' recipe.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </span>
    <h1>{{ recipe.title }}</h1>
    {% if recipe.content_type %}
    <img style="float:right; max-width:50%;" src="{% url 'onestop:recipe_picture' recipe.id %}" onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <p>
    {{ recipe.text|safe }} <!-- RitchText -->
    </p>
    {% if recipe.tags.all %}
    <p>Tags:
        {% for tag in recipe.tags.all %}
        <!-- https://django-taggit.readthedocs.io/en/latest/forms.html
        https://dev.to/tikam02/how-to-implement-django-search-field-and-tags-keywords-286a -->
        <span style="background-color: rgb(236, 147, 31); display: inline-block; border-radius: 3px; font-size: 100%; font-weight: 500; padding: 0 4px; color: rgb(252, 252, 244);">{{ tag }}</span>
        {% endfor %}
    </p>
    {% endif %}
    <p>
        <a href="{{ recipe.website }}" target="_blank">Website</a>
    </p>
    {% if not user.is_authenticated %}
    <p>
        <a href="{% url 'onestop:all' %}">All Recipes</a>
    </p>
    {% endif %}
    {% if user.is_authenticated %}
    <br clear="all"/>
    <p>
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'onestop:recipe_note_create' recipe.id %}">
            {% csrf_token %}
            {{ note_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="All Recipes" onclick="window.location.href='{% url 'onestop:all' %}';return false;">
        </form>
    </p>
    {% endif %}
    {% for note in notes %}
    <p> {{ note.text }}
        ({{ note.updated_at|naturaltime }})
        {% if user == note.owner %}
        <a href="{% url 'onestop:recipe_note_delete' note.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </p>
    {% endfor %}
</div>
{% endblock %}

mysite/onestop/templates/onestop/recipe_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <p>
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}  <!-- RitchText -->
            {{ form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'onestop:all' %}';return false;">
        </form>
    </p>
</div>
<!-- https://docs.djangoproject.com/en/4.1/howto/static-files/ -->
{% load static %}
<!-- https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#json-script -->
{{ form.upload_field_name|json_script:"upload-field-name" }}
{{ form.max_upload_limit|json_script:"max-upload-limit" }}
<script src="{% static 'js/script_recipe_form.js' %}" defer></script>

{% endblock %}

mysite/onestop/templates/onestop/recipe_list.html
{% extends "base_menu.html" %}

{% block content %}
{% load static %}
<div class="container" style="height: 91vh; border-radius: 10px; background-image: url('{% static "/img/recipe_background.jpg" %}');">
    <h1>Recipes</h1>
    <h3>To use full functionality, please log in</h3>
    <div style="float: right; margin-left: 10%;">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
        <form>
            <input type="text" placeholder="Simple Title Search.." name="search" {% if search %} value="{{ search }}" {% endif %}>
            <button type="submit"><i class="fa fa-search"></i></button>
            <a href="{% url 'onestop:all' %}"><i class="fa fa-undo"></i></a>
        </form>
        <br/>
        <p><strong>Favorites Filter</strong>
            <a href="#" title="filter recipes by favorite (just a DOM manipulation)" id="sort-favarite">
                <span class="fa-stack">
                    <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                    <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
            </a>
            <a href="{% url 'onestop:all' %}" title="undo favorite filter on recipes (HTTP GET)">
                <i class="fa fa-undo"></i>
            </a>
        </p>
    </div>
    <p>
        {% if recipe_list %}
        <ul id="registered-recipe-list">
            {% for recipe in recipe_list %}
            <li style="display: block;" id="{{ recipe.id }}">
                <a href="{% url 'onestop:recipe_detail'  recipe.id %}" style="color: black;">{{ recipe.title }}</a>
                {% if recipe.owner == user %}
                (<a href="{% url 'onestop:recipe_update' recipe.id %}" style="color: black;">Edit</a> |
                <a href="{% url 'onestop:recipe_delete' recipe.id %}" style="color: black;">Delete</a>)
                {% endif %}
                {% if user.is_authenticated %}
                <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                <a href="#" onclick=
                    "favPost('{% url 'onestop:recipe_unfavorite' recipe.id %}', {{ recipe.id }});return false;"
                    {% if recipe.id not in favorites %} style="display: none;" {% endif %}
                    id="favorite_star_{{recipe.id}}">
                    <span class="fa-stack" style="vertical-align: middle;">
                        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                        <i class="fa fa-star-o fa-stack-1x"></i>
                    </span>
                </a>
                <!-- the second href -->
                <a href="#" onclick=
                    "favPost('{% url 'onestop:recipe_favorite' recipe.id %}', {{ recipe.id }} );return false;"
                    {% if recipe.id in favorites %} style="display: none;" {% endif %}
                    id="unfavorite_star_{{recipe.id}}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
        {% else %}
        <p>There are no recipes in the database.</p>
        {% endif %}
    </p>
    <br/>
    <p>
        <a href="{% url 'onestop:recipe_create' %}" style="color: black;">Add a Recipe</a> |
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next={% url 'onestop:all' %}" style="color: black;">Logout</a>
        {% else %}
        <a href="{% url 'login' %}?next={% url 'onestop:all' %}" style="color: black;">Login</a>
        {% endif %}
    </p>
    <P>
    <a href="{% url 'onestop:tag_list' %}" style="color: black;">Recipes by Tag (Tag List)</a>
    </p>
</div>
<!-- https://docs.djangoproject.com/en/4.1/howto/static-files/ -->
{% load static %}
<!-- https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#json-script -->
{{ favorites|json_script:"favorites-json" }}
<script src="{% static 'js/script_recipe_list.js' %}" defer></script>
{% endblock %}

mysite/onestop/templates/onestop/tag_list.html
{% extends "base_menu.html" %}

{% block content %}
<div class="container">
    <h1>Recipes by Tag (Tag List)</h1>
    <ul>
        {% for tag in tag_list %}
        <li style="display: block;"><a href="{% url 'onestop:recipe_by_tag_list' tag.name %}">{{ tag.name }}</a></li>
        {% empty %}
        <ol>No tags yet.</ol>
        {% endfor %}
    </ul>
    <br/>
    <p>
        <a href="{% url 'onestop:all' %}">All Recipes</a>
    </p>

    {% if user.is_authenticated and user.is_superuser%}
    <p>
        <a href="{% url 'onestop:delete_unused_tags' %}">Delete unused tags!</a>
    </p>
    {% elif user.is_authenticated and not user.is_superuser%}
    <p>To delete unused tags, please log in with a superuser account | <a href="{% url 'logout' %}?next={% url 'login' %}?next={% url 'onestop:tag_list' %}">Logout</a></p>
    {% else %}
    <p>To delete unused tags, please log in with a superuser account | <a href="{% url 'login' %}?next={% url 'onestop:tag_list' %}">Login</a></p>
    {% endif %}
</div>
{% endblock %}