mysite/daisy/urls.py
from django.urls import path
from . import views

app_name='daisy'
urlpatterns = [
    path('', views.PicListView.as_view(), name='all'),
    path('pic/<int:pk>', views.PicDetailView.as_view(), name='pic_detail'),
    path('pic/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='pic_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(), name='pic_comment_delete'),
]

mysite/home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('register', views.register, name="register"), # message sample: https://learndjango.com/tutorials/django-signup-tutorial
    path('about', views.TechView.as_view(), name="tech"), # django async with token version: https://youtu.be/28KFBqi2JrA?t=900 
    # path('about', TemplateView.as_view(template_name = "home/tech_list.html"), name="tech"), # javascript async with no token version
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from todo.apis import LoginTodoView, LogoutTodoView
from daisy.apis import LoginView, LogoutView
from django.conf.urls.static import static

urlpatterns = [
    # path('', include('ads.urls')),
    path('', include('home.urls')),
    path('onestop/', include('onestop.urls')),
    path('daisy/', include('daisy.urls')),
    path('api/v1/', include('daisy.api_urls')),
    path('api/v1/auth/login/', LoginView.as_view()),
    path('api/v1/auth/logout/', LogoutView.as_view()),
    path('plant/', include('plant.urls')),
    path('admin/', admin.site.urls),
    # https://learndjango.com/tutorials/django-login-and-logout-tutorial
    # https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views
    path('api/v2/', include('todo.api_urls')),
    path('api/v2/auth/login/', LoginTodoView.as_view()),
    path('api/v2/auth/logout/', LogoutTodoView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# urlpatterns += [
#     re_path(r'^apps/(?P<path>.*)$', serve,
#         {'document_root': os.path.join(BASE_DIR, '../'),
#          'show_indexes': True},
#         name='index_path'
#         ),
# ]

# Serve the favicon -
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# https://itc.tokyo/django/setup-media-root/
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References
# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/daisy/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings #https://learndjango.com/tutorials/django-best-practices-referencing-user-model, https://docs.djangoproject.com/en/4.0/topics/signals/


class Pic(models.Model) :
    title = models.CharField(
            max_length=200,
            null=True,
    )
    # Picture
    pic = models.ImageField(upload_to='', null=True, blank=True)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model) :
    comment = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    pic = models.ForeignKey(Pic, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.comment) < 15 : return self.comment
        return self.comment[:11] + ' ...'

mysite/daisy/forms.py
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

mysite/daisy/views.py
from daisy.models import Pic, Comment
from onestop.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.humanize.templatetags.humanize import naturaltime
from daisy.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse


class PicListView(View):
    template_name = "daisy/pic_list.html"

    def get(self, request):
        flash_list = Pic.objects.all().order_by('-created_at')[:5]
        update_list = Pic.objects.exclude(pic="").order_by('-updated_at')[:9]
        ctx = {'flash_list' : flash_list, 'update_list': update_list}
        return render(request, self.template_name, ctx)


class PicDetailView(OwnerDetailView):
    model = Pic
    template_name = "daisy/pic_detail.html"
    
    def get(self, request, pk) :
        x = Pic.objects.get(id=pk)
        comments = Comment.objects.filter(pic=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'pic' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        x = get_object_or_404(Pic, id=pk)
        comment = Comment(comment=request.POST['comment'], owner=request.user, pic=x)
        comment.save()
        return redirect(reverse('daisy:pic_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "daisy/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        pic = self.object.pic
        return reverse('daisy:pic_detail', args=[pic.id])

mysite/daisy/templates/daisy/comment_delete.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Delete Note</h1>
<p>Are you sure you want to delete</p>
<p>{{ comment.comment }}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit"  class="btn btn-primary" value="Yes, delete.">
    <a href="{% url 'daisy:pic_detail' comment.pic.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

mysite/daisy/templates/daisy/pic_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/pic_detail.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    {% if pic.pic %}
    <div id="overlay" class="overlay" style="text-align: center;"
    onclick="document.getElementById('overlay').style.display = 'none';" >
    <img style="width:90%;margin-top: 50px; border:3px solid black;" src="/media/{{ pic.pic }}">
    </div>
    {% endif %}
    <h1>{{ pic.title }}</h1>
    {% if pic.pic %}
    <!-- https://itc.tokyo/django/read-css-file/ -->
    <img style="float:right; max-width:50%;" src="/media/{{ pic.pic }}" 
        onclick="document.getElementById('overlay').style.display = 'block';">
    <p>{{ pic.pic }}</p>
    {% else %}
    <p>Evidence is under review for this move.</p>
    {% endif %}
    {% if not user.is_authenticated %}
    <p>
        <a href="{% url 'daisy:all' %}">All Cats</a>
    </p>
    {% endif %}
    {% if user.is_authenticated %}
    <br clear="all"/>
    <p>
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'daisy:pic_comment_create' pic.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit Your Comment">
            <input type="submit" value="All Cats" onclick="window.location.href='{% url 'daisy:all' %}';return false;">
        </form>
    </p>
    {% endif %}
    {% for comment in comments %}
    <p> &#x1f431; Comment: {{ comment.comment }}
        (by {{ comment.owner }}, {{ comment.updated_at|naturaltime }})
        {% if user == comment.owner %}
        <a href="{% url 'daisy:pic_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </p>
    {% endfor %}
</div>
{% endblock %}

mysite/daisy/templates/daisy/pic_list.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %} 
<!-- slider: https://coco-factory.jp/ugokuweb/move01/9-4-1/ -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.css">
{% load static %}
<link rel="stylesheet" href="{% static 'css/pic_list_slider.css' %}">
<!-- slider: -->
<link rel="stylesheet" href="{% static 'css/pic_list_3d_slide.css' %}">
<!-- loader -->
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
{% endblock %}

{% block content %}
<div class="loading container">
    <span class="circle"></span>
</div>
<div class="container" id="main-container">
    <h1>Cat Monitor</h1>
    <h3>Let's see what she does everyday while she is out of our sight.... To use full functionality, please log in</h3>
    <br/>
    <h2>1. The Flash - New Cat Moves: A Motion Deteced the Evidence Pic Is Under Review Before Published!</h2>
    <h3>&#x26a1; Latest: <a href="{% url 'daisy:pic_detail' flash_list.0.id %}">{{ flash_list.0.title }} ({{ flash_list.0.created_at|naturaltime }})</a> &#x26a1;</h3>
    <!-- スライド -->
    <div class="wrapper">
        <ul class="slider">
            {% for pic in flash_list %}
            <li><a href="{% url 'daisy:pic_detail' pic.id %}"><span>{{ pic.created_at }}</span>&#x1f195; {{ pic.title }} &#x1f4f8;</a></li>
            {% endfor %}
        </ul>
    </div>
    <h2>2. Updates - Hard Evidece Added: Evidence Pics Added to the Records Below.</h2>
    <h3>&#x26a1; Latest: <a href="{% url 'daisy:pic_detail' update_list.0.id %}">{{ update_list.0.title }} ({{ update_list.0.updated_at|naturaltime }})</a> &#x26a1;</h3>
    <div class="wrapper">
        <ul class="slider">
            {% for pic in update_list %}
            <li><a href="{% url 'daisy:pic_detail' pic.id %}"><span>{{ pic.updated_at }}</span>&#x1f575; {{ pic.title }} &#x26a0;</a></li>
            {% endfor %}
        </ul>
    </div>
    <!-- 3D Slideshow Section -->
    <!-- https://codepen.io/jaskiranchhokar/pen/wmGXav -->
    <h2>3. Cat Moves With Hard Evidence</h2>
    <div id="slideshow">
        <div class="entire-content">
            <div class="content-carrousel">
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.0.id %}"><img src="/media/{{ update_list.0.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.1.id %}"><img src="/media/{{ update_list.1.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.2.id %}"><img src="/media/{{ update_list.2.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.3.id %}"><img src="/media/{{ update_list.3.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.4.id %}"><img src="/media/{{ update_list.4.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.5.id %}"><img src="/media/{{ update_list.5.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.6.id %}"><img src="/media/{{ update_list.6.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.7.id %}"><img src="/media/{{ update_list.7.pic }}" class="card-img-top" alt="..."></a></figure>
                <figure class="shadow"><a href="{% url 'daisy:pic_detail' update_list.8.id %}"><img src="/media/{{ update_list.8.pic }}" class="card-img-top" alt="..."></a></figure>
            </div>
        </div>
    </div>  
</div>
<!-- slider: https://coco-factory.jp/ugokuweb/move01/9-4-1/ -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.js"></script>
{% load static %}
<script src="{% static 'js/slider.js' %}"></script>
<script src="{% static 'js/loader.js' %}"></script>
<!-- slider: -->
{% endblock %}