mysite/daisy/urls.py
from django.urls import path
from . import views

app_name='daisy'
urlpatterns = [
    path('', views.PicListView.as_view(), name='all'),
    path('pic/<int:pk>', views.PicDetailView.as_view(), name='pic_detail'),
    path('pic/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='pic_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(), name='pic_comment_delete'),
]

mysite/home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('register', views.register, name="register"), # message sample: https://learndjango.com/tutorials/django-signup-tutorial
    path('about', views.TechView.as_view(), name="tech"), # django async with token version: https://youtu.be/28KFBqi2JrA?t=900 
    # path('about', TemplateView.as_view(template_name = "home/tech_list.html"), name="tech"), # javascript async with no token version
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from todo.apis import LoginTodoView, LogoutTodoView
from daisy.apis import LoginView, LogoutView
from django.conf.urls.static import static

urlpatterns = [
    # path('', include('ads.urls')),
    path('', include('home.urls')),
    path('onestop/', include('onestop.urls')),
    path('daisy/', include('daisy.urls')),
    path('api/v1/', include('daisy.api_urls')),
    path('api/v1/auth/login/', LoginView.as_view()),
    path('api/v1/auth/logout/', LogoutView.as_view()),
    path('plant/', include('plant.urls')),
    path('admin/', admin.site.urls),
    # https://learndjango.com/tutorials/django-login-and-logout-tutorial
    # https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views
    path('api/v2/', include('todo.api_urls')),
    path('api/v2/auth/login/', LoginTodoView.as_view()),
    path('api/v2/auth/logout/', LogoutTodoView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# urlpatterns += [
#     re_path(r'^apps/(?P<path>.*)$', serve,
#         {'document_root': os.path.join(BASE_DIR, '../'),
#          'show_indexes': True},
#         name='index_path'
#         ),
# ]

# Serve the favicon -
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# https://itc.tokyo/django/setup-media-root/
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References
# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/onestop/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='onestop'
urlpatterns = [
    path('', views.RecipeListView.as_view(), name='all'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipe/create',
        views.RecipeCreateView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_create'),
    path('recipe/<int:pk>/update',
        views.RecipeUpdateView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_update'),
    path('recipe/<int:pk>/delete',
        views.RecipeDeleteView.as_view(success_url=reverse_lazy('onestop:all')), name='recipe_delete'),
    path('recipe-picture/<int:pk>', views.stream_file, name='recipe_picture'),
    path('recipe/<int:pk>/note',
        views.NoteCreateView.as_view(), name='recipe_note_create'),
    path('note/<int:pk>/delete',
        views.NoteDeleteView.as_view(), name='recipe_note_delete'),
    path('recipe/<int:pk>/favorite', views.AddFavoView.as_view(), name='recipe_favorite'),
    path('recipe/<int:pk>/unfavorite', views.DeleteFavoView.as_view(), name='recipe_unfavorite'),
    path('tags/', views.TagListView.as_view(), name='tag_list'), # https://django-taggit.readthedocs.io/en/latest/api.html
    path('tags/<str:name>/recipes', views.RecipeByTagListView.as_view(), name='recipe_by_tag_list'), # https://github.com/jazzband/django-taggit/issues/294
    path('tags/delete/unused-tags', views.remove_all_tags_without_objects, name='delete_unused_tags'),
]

#Use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/plant/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name='plant'
urlpatterns = [
    path('', TemplateView.as_view(template_name="plant_list.html"), name='all'),
]

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# https://ordinarycoders.com/blog/article/django-user-register-login-logout
class NewUserForm(UserCreationForm):
	email = forms.EmailField(label='email', required=False)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

mysite/home/views.py
from django.shortcuts import  render, redirect
from django.views import View
from django.conf import settings
from django.contrib import messages  
from django.urls import reverse_lazy
from django.contrib.auth import login
from home.forms import NewUserForm
import asyncio
import aiohttp
import time
from django.utils.decorators import classonlymethod
from asgiref.sync import sync_to_async
##Rate Limit: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting
## To check the rate limit 
## curl -i -H "Authorization: token YOUR_TOKEN" https://api.github.com/repos/Tak2009/django-1/languages
from mysite.settings import PERSONAL_ACCESS_TOKEN


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)


# Step 1: Func based async. then connverted to Class based 
# https://www.youtube.com/watch?v=28KFBqi2JrA&list=RDCMUC1mxuk7tuQT2D0qTMgKji3w&start_radio=1&rv=28KFBqi2JrA&t=0
class TechView(View):
    template_name = "home/tech_list_dj_asyn_version.html"
    urls = [
        "https://api.github.com/repos/Tak2009/django-1/languages",
        "https://api.github.com/repos/Tak2009/raspi-2-motion-detect-sensor-oauth2-tk/languages",
        "https://api.github.com/repos/Tak2009/raspi-3-moisture-sensor-client-tk/languages",
        "https://api.github.com/repos/Tak2009/raspi-3-water-pump-server-tk/languages"
    ]

    ## Step2: The view home.views.view didn't return an HttpResponse object. It returned an unawaited coroutine instead. You may need to add an 'await' into your view.
    ## https://medium.com/@bruno.fosados/django-async-class-based-views-acbv-5986c4511ae6 ####
    ## https://stackoverflow.com/questions/62038200/correct-way-to-use-async-class-based-views-in-django ####
    @classonlymethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        view._is_coroutine = asyncio.coroutines._is_coroutine
        return view
    ##

    ## Step 3: https://stackoverflow.com/questions/5376985/django-request-user-is-always-anonymous-user
    ## You cannot call this from an async context - use a thread or sync_to_async at {% if user.is_authenticated %}
    @sync_to_async
    def get_user_from_request(self, request):
        return request.user if bool(request.user) else None
    ##

    async def get_github(self, session, url):
        async with session.get(url) as res:
            github_data = await res.json()
            return {url: github_data}
    
    def CalcRatio(self, languages_dict):
        total = sum((languages_dict.values()))
        lang_ratio_by_project = {}
        for lang in languages_dict:
             lang_ratio_by_project[lang] = "{}".format(round(int(languages_dict[lang])/total * 100, 2))
        return lang_ratio_by_project

    async def get(self, request):
        starting_time = time.time()
        actions = []
        github_data_list = []
        project_list = {}

        ## Step3: https://stackoverflow.com/questions/5376985/django-request-user-is-always-anonymous-user
        ## You cannot call this from an async context - use a thread or sync_to_async at {% if user.is_authenticated %}
        user = await self.get_user_from_request(request)
        ##

        headers={"Authorization": "token " + PERSONAL_ACCESS_TOKEN}
        async with aiohttp.ClientSession(headers=headers) as session:
            for url in self.urls:
                actions.append(asyncio.ensure_future(self.get_github(session, url)))
            github_res = await asyncio.gather(*actions)
            for data in github_res:
                github_data_list.append(data)
        count = len(github_data_list)
        total_time = time.time() - starting_time
    
        # change the data structure
        for i, v in enumerate(github_data_list):
            print(i, v)
            old_key = list(v.keys())[0]
            new_key = old_key[old_key.find('Tak2009/')+len('Tak2009/'): -len('/languages')]
            # calc ratio
            lang_ratio_by_project = self.CalcRatio(v[old_key])
            project_list[new_key] = lang_ratio_by_project
        # print(project_list)
            
        return render(
            request,
            self.template_name,
            {"project_list": project_list, "count": count, "process_time": total_time},
        )


def register(request):
	template_name = "home/register.html"
	success_url = reverse_lazy('home:all')
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect(success_url)
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	context={"form":form}
	return render (request, template_name, context)

mysite/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="dRKZC_iJlXkjf2SAQK2Lpx9-lp_3nn9RZ-6UOKI6lB4" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- ### for $.post in recipe_list.html ###-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <script>
        // 1. ajax.googleapis.com 3.3.1に対してエイリアスを設定: https://www.buildinsider.net/web/jqueryref/068; https://qiita.com/mijabi/items/c68d27bc2ea5642675af
        var $j = jQuery.noConflict(true);
    </script>
    <!--  -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

    <!-- Pannellum: https://pannellum.org/documentation/examples/simple-example/ -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
    <!--  -->

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

{% block head %} {% endblock %}

</head>
<body>
    <div class="container">
    {% block navbar %} {% endblock %}
    {% block welcome %} {% endblock %}
    {% block messages %}
        {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}}" role="alert">
            {{msg.message}}
            </div>
        {% endfor %}
        {% endif %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    </div>
    {% block footer %} {% endblock %}
</body>
</html>

mysite/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}

{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3" style="border-radius: 10px;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    <!-- https://knowledge.cpi.ad.jp/tech/navbar/ -->
    <!-- https://medium-company.com/bootstrap-navbar/ -->
        <div class="collapse navbar-collapse justify-content navbarNav4">
            <div class="navbar-nav">
                {% url 'home:all' as home %}
                <a class="nav-item nav-link" {% if request.get_full_path == home %}class="active"{% endif %} href="{% url 'home:all' %}">
                    Home
                </a>
                {% url 'onestop:all' as recipe %}
                <a class="nav-item nav-link" {% if request.get_full_path == recipe %}class="active"{% endif %} href="{% url 'onestop:all' %}">
                    Recipes
                </a>
                {% url 'daisy:all' as daisy %}
                <a class="nav-item nav-link" {% if request.get_full_path == daisy %}class="active"{% endif %} href="{% url 'daisy:all' %}">
                    Cat Monitor
                </a>
                {% url 'plant:all' as plant %}
                <div style="display: inline-block;">
                    <a class="nav-item nav-link" {% if request.get_full_path == plant %}class="active"{% endif %} href="{% url 'plant:all' %}">
                        Plant Watering
                    </a>
                </div>
                {% url 'home:tech' as tech %}
                <div style="display: inline-block;">
                    <a class="nav-item nav-link" {% if request.get_full_path == tech %}class="active"{% endif %} href="{% url 'home:tech' %}">Tech Info
                        <img src="/static/img/github-mark-white.png" width="7%" height="7%" alt="...">
                    </a>
                </div>
            </div>
        </div>
        <div class="collapse navbar-collapse justify-content-end navbarNav4">
            {% if user.is_authenticated %}
            <div class="navbar-nav dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create Menu</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'onestop:recipe_create' %}">Create Recipe</a>
                </div>
            </div>
            <div class="navbar-nav dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
                </a>
                
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'logout' %}?next={% url 'home:all' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <div class="navbar-nav dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'home:register' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'login' %}?next={% url 'home:all' %}">Login</a>
                </div>
            </div>
            {% endif %}
        </div>
    </nav>
{% endblock %}